### ISSUE TITLE
:var does not work for defcustom?

### ISSUE THREAD

**Issue by Trevoke** [jorgenschaefer/emacs-buttercup#206] opened 2021-10-23 13:00 UTC
I have discovered in my test suite ( https://github.com/trevoke/org-gtd.el/ ) that I couldn't use `:var org-gtd-directory` to set the variable -- in my tests, it wouldn't be the correct value, it would be the default value. `org-gtd-directory` is a `defcustom`, so it has a default value that I was trying to change within a describe block.

So right now instead I accept that I am modifying the global scope and setting that variable with `setq` in a function called by `before-all`.

This is... Fine... But it lowers my overall trust in buttercup as a test runner :/ 

Here is sample code:

```elisp
;; -*- lexical-binding: t; -*-

(require 'buttercup)
(require 'org-gtd)

(describe
 "Org GTD"

 :var ((org-gtd-directory (f-join default-directory "test"  "runtime-file-path")))

 (it "Creates a default file for each action where there isn't a refile target"
     (message org-gtd-directory)))
```

This prints out `~/gtd` instead of `~/src/projects/org-gtd.el/test/runtime-file-path`.

**Comment by Trevoke** [comment] 2021-10-30 00:14
I don't think so, because I have lexical binding enabled?

**Comment by Trevoke** [comment] 2021-10-30 00:15
It's also possible I've actually misunderstood the flow of conversation in #127 and the core issue is still the dynamic scope, if so, then yes, I would agree it's a duplicate. I am not that familiar with emacs internals yet.

**Comment by snogge** [comment] 2022-01-29 13:17
This is not about lexical binding, lexical binding is required for buttercup to work. I'm going to say that this

**Comment by snogge** [comment] 2022-01-29 13:18
Duplicate of #127

**Comment by snogge** [comment] 2022-03-05 12:32
Closing as a duplicate

**Closed by snogge** 2022-03-05 12:32 UTC
